experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_indexed.tsv
    validation_path: ../data/{0}/val_indexed.tsv
    test_path: ../data/{0}/test_indexed.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/visual_embeddings_random_complete_indexed
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/textual_embeddings_random_complete_indexed
  dataset: Beauty
  top_k: 20
  evaluation:
    cutoffs: [ 20 ]
    simple_metrics: [ Recall, nDCG, Precision ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.BM3:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      multimod_factors: 64
      reg_weight: [ 0.1, 0.01 ]
      cl_weight: 2.0
      dropout: 0.3
      n_layers: 2
      modalities: ('visual', 'textual')
      loaders: ('VisualAttribute','TextualAttribute')
      epochs: 200
      factors: 64
      lr_sched: (1.0,50)
      batch_size: 1024
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: Recall@20
        verbose: True