experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_indexed.tsv
    validation_path: ../data/{0}/val_indexed.tsv
    test_path: ../data/{0}/test_indexed.tsv
    side_information:
      - dataloader: VisualAttribute
        visual_features: ../data/{0}/visual_embeddings_zeros_complete_indexed
      - dataloader: TextualAttribute
        textual_features: ../data/{0}/textual_embeddings_zeros_complete_indexed
  dataset: Digital_Music
  top_k: 20
  evaluation:
    cutoffs: [ 20 ]
    simple_metrics: [ Recall, nDCG, Precision ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.FREEDOM:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      factors: 64
      epochs: 200
      l_w: [ 1e-5, 1e-2 ]
      n_layers: 1
      n_ui_layers: 2
      top_k: 10
      factors_multimod: 64
      modalities: ('visual', 'textual')
      loaders: ('VisualAttribute','TextualAttribute')
      mw: (0.1,0.9)
      drop: 0.8
      lr_sched: (1.0,50)
      batch_size: 1024
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: Recall@20
        verbose: True