experiment:
  backend: pytorch
  data_config:
    strategy: fixed
    train_path: ../data/{0}/train_indexed.tsv
    validation_path: ../data/{0}/val_indexed.tsv
    test_path: ../data/{0}/test_indexed.tsv
  dataset: Beauty
  top_k: 20
  evaluation:
    cutoffs: [ 20 ]
    simple_metrics: [ Recall, nDCG, Precision ]
  gpu: 0
  external_models_path: ../external/models/__init__.py
  models:
    external.SGL:
      meta:
        hyper_opt_alg: grid
        verbose: True
        save_weights: False
        save_recs: False
        validation_rate: 1
        validation_metric: Recall@20
        restore: False
      epochs: 200
      batch_size: 1024
      factors: 64
      lr: [ 0.0001, 0.0005, 0.001, 0.005, 0.01 ]
      l_w: [ 1e-5, 1e-2 ]
      n_layers: 3
      ssl_temp: 0.2
      ssl_reg: 0.1
      ssl_ratio: 0.1
      sampling: ed
      seed: 123
      early_stopping:
        patience: 5
        mode: auto
        monitor: Recall@20
        verbose: True